datomic:
  image: mayopta/datomic-transactor
  expose:
    - 4334
    - 4335
    - 4336
  volumes:
    - /var/library-asset-tags:/var/datomic

app:
  image: mayopta/library-asset-tag
  links:
    - datomic
  ports:
    - 3000:3000
  environment:
    - LAT_HTTP_PORT=3000
    - LAT_DB_URL=datomic:free://datomic:4334/library
